# -*- coding: utf-8 -*-
"""Practice_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iL6lMp2uULbmOxtk0i3SfzeOnUXo50WE

importing libraries needed
"""

import numpy as np
import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/placement-project-logistic-regression/main/placement.csv")
df.head()
df.shape
df.info()

"""removing first colums as it is of no use """

df=df.iloc[:,1:]
df.head()
df.shape

"""plotting a scatter grapph"""

import matplotlib.pyplot as plt
plt.scatter(df['cgpa'],df['iq'],c=df['placement'])
x= df.iloc[:,0:2]
y= df.iloc[:,-1]

"""dividing 10% of values for test of x and y and having 90% for training of the model"""

from sklearn.model_selection import train_test_split 
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

"""standard scaler is used to fit values in the range of -1 to 1"""

from sklearn.preprocessing import StandardScaler 
scale = StandardScaler()
x_train= scale.fit_transform(x_train)
x_test= scale.transform(x_test)

"""Logistic Regression is th ML model used as"""

from sklearn.linear_model import LogisticRegression
clf= LogisticRegression()
clf.fit(x_train ,y_train)

"""giving x_test values for testing model and saving it in y_prediction"""

y_pred= clf.predict(x_test)

"""accuracy is called between y_test and y_pred"""

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

"""plotting graph to see where the ML has drawn the division line """

from mlxtend.plotting import plot_decision_regions
plot_decision_regions(x_train,y_train.values , clf=clf , legend = 2)

"""save the ML model as a pkl file to deploy"""

import pickle
pickle.dump(clf,open('model.pkl','wb'))